#!/bin/bash
echo $(($BREATH 0-alias 10-love_exponent_breath 1-hello_you 2-path 3-paths 4-global_variables 5-local_variables 6-create_local_variable 7-create_global_variable 8-true_knowledge 9-divide_and_rule myscript.sh README.md $LOVE))
