#!/usr/bin/env bash
# Fixes listening port of Ngnix server


sudo sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sudo sed -i '22d' /etc/nginx/sites-enabled/default
sudo service nginx start
